language: java

jdk:
  - oraclejdk7

services:
  - mysql

branches:
  only:
    - master

before_install:
  - find . -type f -print0 | xargs -0 sed -i "s/DYNAMIC-SNAPSHOT/1.0.${TRAVIS_BUILD_NUMBER}/g"

install: "mvn package -Dmaven.javadoc.skip=true -B -V"

before_script:
  - curl -o tomcat.tar.gz -L http://ftp.piotrkosoft.net/pub/mirrors/ftp.apache.org/tomcat/tomcat-7/v7.0.68/bin/apache-tomcat-7.0.68.tar.gz
  - curl -o mysql.jar -L http://repo1.maven.org/maven2/mysql/mysql-connector-java/5.1.38/mysql-connector-java-5.1.38.jar
  - tar -zxf tomcat.tar.gz
  - mv ./mysql.jar ./lib
  - cp ./.travis/context.xml ./apache-tomcat-7.0.68/conf
  - bash ./apache-tomcat-7.0.68/bin/startup.sh
  - mysql -e 'create database test;'

script:
  - cp ./target/spray-test.war ./apache-tomcat-7.0.68/webapps
  - sleep 45
  - python ./src/test/integration/run.py || exit 1
