CREATE TABLE CAT_GROUP (
  ID BIGINT PRIMARY KEY,
  NAME VARCHAR(50) NOT NULL
);

CREATE TABLE CAT (
  ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(50) NOT NULL,
  GROUP_ID BIGINT NOT NULL REFERENCES CAT_GROUP(ID),
  BIRTH_DATE DATETIME NOT NULL,

  FOREIGN KEY FK_GROUP (GROUP_ID) REFERENCES CAT_GROUP(ID)
);

INSERT INTO CAT_GROUP VALUES (1, 'Bandits');
INSERT INTO CAT_GROUP VALUES (2, 'Claws');
